name: Trigger GitLab CI

on:
  push:
    branches:
      - main  # ou outro branch que você quiser monitorar

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST "https://gitlab.com/api/v4/projects/71768781/trigger/pipeline" \
            --form token=$GITLAB_TOKEN \
            --form ref=main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
